version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      SWAGGER_JSON: /app/swagger.yml
    volumes:
      - ./swagger.yml:/app/swagger.yml
